from pathlib import Path


def write_dummy_transcripts(job_dir: Path, job_id: str) -> tuple[Path, Path]:
    md_path = job_dir / "transcript_speakers.md"
    txt_path = job_dir / "transcript_clean.txt"

    md_path.write_text(
        f"# Transcript {job_id}\n\n"
        "LLM post-processing is not connected yet.\n\n"
        "This is a dummy transcript generated by the MVP worker.\n",
        encoding="utf-8",
    )
    txt_path.write_text(
        f"Transcript {job_id}\n\n"
        "LLM post-processing is not connected yet.\n"
        "This is a dummy transcript generated by the MVP worker.\n",
        encoding="utf-8",
    )
    return md_path, txt_path
